import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";

import "./globals.css";

import Head from "next/head";

import { TooltipProvider } from "~/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Patiently",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
    <html lang="en" className={`${GeistSans.variable}`}>
      <Head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </Head>
      <body>
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
