export const DATA: Array<{
  // id: string;
  name: string;
  title: string;
  status: "Active" | "Inactive";
  role: "Physician" | "Nurse" | "Secretary" | "Manager";
}> = [
  {
    // id: "1",
    name: "Sterling Everett",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "2",
    name: "Christina Martinez",
    title: "Physician",
    status: "Active",
    role: "Nurse",
  },
  {
    // id: "3",
    name: "Soren Poole",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "4",
    name: "Jordyn Gaines",
    title: "Physician",
    status: "Active",
    role: "Secretary",
  },
  {
    // id: "5",
    name: "Thaddeus Shepherd",
    title: "Physician",
    status: "Inactive",
    role: "Nurse",
  },
  {
    // id: "6",
    name: "Florence Blair",
    title: "Physician",
    status: "Inactive",
    role: "Physician",
  },
  {
    // id: "7",
    name: "Elisha Horton",
    title: "Physician",
    status: "Inactive",
    role: "Manager",
  },
  {
    // id: "8",
    name: "Alivia Giles",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "9",
    name: "Cain Patterson",
    title: "Physician",
    status: "Active",
    role: "Nurse",
  },
  {
    // id: "10",
    name: "Oaklee Durham",
    title: "Physician",
    status: "Active",
    role: "Secretary",
  },
  {
    // id: "11",
    name: "Dalton Davidson",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "12",
    name: "Penelope McClure",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "13",
    name: "Clay Morton",
    title: "Physician",
    status: "Active",
    role: "Nurse",
  },
  {
    // id: "14",
    name: "Genesis Hobbs",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "15",
    name: "Ashton Franklin",
    title: "Physician",
    status: "Active",
    role: "Secretary",
  },
  {
    // id: "16",
    name: "Julieta Hendricks",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "17",
    name: "Michael Bartlett",
    title: "Physician",
    status: "Active",
    role: "Nurse",
  },
  {
    // id: "18",
    name: "Kimberly Howard",
    title: "Physician",
    status: "Active",
    role: "Secretary",
  },
  {
    // id: "19",
    name: "Dane Lugo",
    title: "Physician",
    status: "Active",
    role: "Manager",
  },
  {
    // id: "20",
    name: "Maci Delgado",
    title: "Physician",
    status: "Active",
    role: "Nurse",
  },
  {
    // id: "21",
    name: "Evan Dejesus",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "22",
    name: "Adley Barber",
    title: "Physician",
    status: "Active",
    role: "Manager",
  },
  {
    // id: "23",
    name: "Kyrie Bowers",
    title: "Physician",
    status: "Active",
    role: "Nurse",
  },
  {
    // id: "24",
    name: "Bailee Howe",
    title: "Physician",
    status: "Active",
    role: "Secretary",
  },
  {
    // id: "25",
    name: "Anthony Medrano",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "26",
    name: "Mazikee Roy",
    title: "Physician",
    status: "Active",
    role: "Nurse",
  },
  {
    // id: "27",
    name: "Kevin Meza",
    title: "Physician",
    status: "Active",
    role: "Manager",
  },
  {
    // id: "28",
    name: "Romina Griffith",
    title: "Physician",
    status: "Active",
    role: "Secretary",
  },
  {
    // id: "29",
    name: "Joziah Frye",
    title: "Physician",
    status: "Active",
    role: "Nurse",
  },
  {
    // id: "30",
    name: "Iyla Long",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "31",
    name: "Landen Chapman",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "32",
    name: "Celia Moreno",
    title: "Physician",
    status: "Active",
    role: "Manager",
  },
  {
    // id: "33",
    name: "Maximiliano Raymond",
    title: "Physician",
    status: "Active",
    role: "Secretary",
  },
  {
    // id: "34",
    name: "Fallon Howard",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "35",
    name: "Reece Lester",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "36",
    name: "Leah Wood",
    title: "Physician",
    status: "Active",
    role: "Secretary",
  },
  {
    // id: "37",
    name: "Jaiden Baldwin",
    title: "Physician",
    status: "Active",
    role: "Manager",
  },
  {
    // id: "38",
    name: "Hana Gaines",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "39",
    name: "Jericho Lucas",
    title: "Physician",
    status: "Active",
    role: "Nurse",
  },
  {
    // id: "40",
    name: "Novalee Palmer",
    title: "Physician",
    status: "Active",
    role: "Secretary",
  },
  {
    // id: "41",
    name: "Karson Pitts",
    title: "Physician",
    status: "Active",
    role: "Physician",
  },
  {
    // id: "42",
    name: "Milani Faulkner",
    title: "Physician",
    status: "Active",
    role: "Nurse",
  },
];

export const pageCount = 2;
